#!/usr/bin/env bash
#
# Blue-green deploy for the Antgrid relay + web on a single Docker host.
#
# Runs on the VM from the deploy dir (default /srv/antgrid). The CI workflow
# rsyncs this dir and invokes:  IMAGE_TAG=<sha> ./deploy.sh
#
# Flow: bring up the idle color -> migrate (expand/contract-safe) -> health-gate
# -> flip Caddy (graceful reload) -> record active color. The previous color is
# left running so rollback is instant (re-point Caddy + reload); the next deploy
# reclaims its slot.
#
# web flip is seamless. The relay holds in-memory connection state and
# runs single-instance, so its clients see a ~1-3s reconnect blip on flip — they
# auto-reconnect. This is expected.
set -euo pipefail

cd "$(dirname "$0")"

IMAGE_TAG="${IMAGE_TAG:-latest}"
# Single source of truth for the environment (prod = antgrid.ai, staging =
# staging.antgrid.ai). Required, never defaulted: a silent prod default let a
# bare manual run on the staging VM act as prod — rendering prod Caddy hosts
# (app.$DOMAIN/relay.$DOMAIN) and starting the prod-only errex. CI sets it
# per-environment; manual runs must pass it (e.g. DOMAIN=antgrid.ai ./deploy.sh).
DOMAIN="${DOMAIN:?set DOMAIN (antgrid.ai for prod, staging.antgrid.ai for staging)}"
EDGE_PROJECT="ab-edge"
NETWORK="antgrid_edge"
STATE_FILE="./ACTIVE"
HEALTH_TIMEOUT="${HEALTH_TIMEOUT:-120}"
APP="-f compose.app.yml"
EDGE="-f compose.edge.yml"
ERREX="-f compose.errex.yml"
ERREX_PROJECT="ab-errex"
MODE="${1:-deploy}"

log() { printf '\033[36m[deploy]\033[0m %s\n' "$*"; }
die() { printf '\033[31m[deploy] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# Render the Caddy site config for a color. Single source of truth for the
# routing file — used by both the forward flip and rollback (no fragile sed).
write_active_caddy() {
	local color="$1"
	mkdir -p caddy/sites
	cat > caddy/sites/active.caddy <<EOF
# Generated by deploy.sh — active color: $color
app.$DOMAIN {
	reverse_proxy web-$color:8787
}

relay.$DOMAIN {
	reverse_proxy relay-$color:8080
}
EOF
}
reload_caddy() {
	docker compose -p "$EDGE_PROJECT" $EDGE exec -T caddy caddy reload --config /etc/caddy/Caddyfile
}

[ -f .env ] || die ".env not found in $(pwd) — copy .env.example and fill it in (chmod 600)."

# Shared edge network (idempotent). The subnet is pinned so TRUSTED_PROXY_IPS
# (relay client-IP recovery — see packages/antgrid-wire/src/client-ip.ts) has a
# stable value that survives host rebuilds; an unpinned network lands on
# whatever subnet docker picks next and silently un-trusts the proxy. Existing
# networks keep their subnet — check `docker network inspect antgrid_edge` and
# set TRUSTED_PROXY_IPS to match (or recreate the network).
docker network inspect "$NETWORK" >/dev/null 2>&1 || {
	log "creating network $NETWORK"
	# Pinning trades docker's free-pool search for a fixed range, so an
	# unrelated network or route already holding it fails the create. Name the
	# remedy here: the raw docker error ("Pool overlaps") does not say that
	# TRUSTED_PROXY_IPS has to move with the subnet.
	docker network create --subnet 172.28.0.0/16 "$NETWORK" >/dev/null || die \
		"could not create $NETWORK with subnet 172.28.0.0/16 (already in use by another network or route?). Pick a free range: 'docker network create --subnet <free>/16 $NETWORK', then set TRUSTED_PROXY_IPS=<free>/16 in .env."
}

# Rollback: re-point Caddy at the previous color (left running by the last flip)
# without rebuilding. Regenerates the routing file from the same template as a
# forward flip, so there is no string-substitution to corrupt.
if [ "$MODE" = rollback ]; then
	current="$(cat "$STATE_FILE" 2>/dev/null || true)"
	case "$current" in
		blue)  prev=green ;;
		green) prev=blue ;;
		*)     die "no active color recorded in $STATE_FILE — nothing to roll back" ;;
	esac
	docker inspect -f '{{.State.Running}}' "web-$prev" >/dev/null 2>&1 \
		|| die "previous color ab-$prev is not running — cannot roll back to it"
	log "rolling back: $current -> $prev"
	docker compose -p "$EDGE_PROJECT" $EDGE up -d >/dev/null
	write_active_caddy "$prev"
	reload_caddy
	echo "$prev" > "$STATE_FILE"
	log "rollback complete. live color = $prev"
	exit 0
fi

# Determine current (active) and target (idle) colors.
active="$(cat "$STATE_FILE" 2>/dev/null || true)"
case "$active" in
	blue)  target=green ;;
	green) target=blue ;;
	*)     active=""; target=blue ;;  # first deploy
esac
log "active=${active:-none} -> deploying target=$target (tag=$IMAGE_TAG)"

wait_healthy() {
	local name="$1" timeout="${2:-$HEALTH_TIMEOUT}" elapsed=0 status
	while true; do
		status="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$name" 2>/dev/null || echo missing)"
		[ "$status" = healthy ] && return 0
		[ "$elapsed" -ge "$timeout" ] && return 1
		sleep 3; elapsed=$((elapsed + 3))
	done
}
rollback_target() {
	log "tearing down failed target ab-$target (active color untouched)"
	COLOR="$target" IMAGE_TAG="$IMAGE_TAG" docker compose -p "ab-$target" $APP down --remove-orphans >/dev/null 2>&1 || true
}

# Reclaim the target slot in case a previous deploy left it half-up.
COLOR="$target" IMAGE_TAG="$IMAGE_TAG" docker compose -p "ab-$target" $APP down --remove-orphans >/dev/null 2>&1 || true

# Bring up the target color.
log "pulling images"
COLOR="$target" IMAGE_TAG="$IMAGE_TAG" docker compose -p "ab-$target" $APP pull
log "starting ab-$target"
COLOR="$target" IMAGE_TAG="$IMAGE_TAG" docker compose -p "ab-$target" $APP up -d

# Migrations run against the shared external DB while the OLD color still serves,
# so they MUST be backward-compatible (expand/contract). prisma migrate deploy
# is idempotent.
log "running web migrations"
docker exec "web-$target" sh -c 'cd /app/web && bun run migrate' \
	|| { rollback_target; die "migrations failed"; }

# Health-gate the target color before sending it any traffic.
log "waiting for health: web-$target, relay-$target"
wait_healthy "web-$target" || { rollback_target; die "web-$target never became healthy"; }
wait_healthy "relay-$target"       || { rollback_target; die "relay-$target never became healthy"; }
log "target healthy"

# Ensure the edge proxy is running (idempotent; safe on first deploy).
docker compose -p "$EDGE_PROJECT" $EDGE up -d >/dev/null

# errex runs ONLY on production (one shared instance; staging crashes go to a
# separate errex *project* on the same host). On prod: ensure it's up before the
# Caddy reload (idempotent; its own project, so the blue-green teardown never
# touches it and its SQLite volume persists). On non-prod: drop the errex site
# block so staging's Caddy doesn't serve it or chase a cert for the prod host.
#
# errex is AUXILIARY: a failed image pull or start must NEVER abort a live
# app+relay flip, so every step here is non-fatal. We still health-check it
# (short, bounded) so a broken container is logged loudly instead of silently
# swallowing crash reports behind Caddy.
if [ "$DOMAIN" = "antgrid.ai" ]; then
	if docker compose -p "$ERREX_PROJECT" $ERREX up -d >/dev/null; then
		wait_healthy errex 30 || log "WARNING: errex did not become healthy in 30s — crash ingest may be degraded (deploy continues)"
	else
		log "WARNING: errex failed to start (check image pull / docker logs errex) — crash reporting unavailable (deploy continues)"
	fi
else
	rm -f caddy/sites/errex.caddy
fi

# Point Caddy at the target color. Back up the current routing first so a failed
# reload can be reverted — keeps the on-disk config == Caddy's running config, so
# a later edge restart can't pick up a color we never actually flipped to.
prev_caddy=""
[ -f caddy/sites/active.caddy ] && prev_caddy="$(cat caddy/sites/active.caddy)"
write_active_caddy "$target"

log "reloading Caddy -> $target"
if ! reload_caddy; then
	# Reload is atomic: Caddy is still serving the previous color. Restore the
	# routing file to match, then fail loudly (ACTIVE is left unchanged).
	if [ -n "$prev_caddy" ]; then printf '%s\n' "$prev_caddy" > caddy/sites/active.caddy
	else rm -f caddy/sites/active.caddy; fi
	die "caddy reload failed — routing reverted, previous color still live"
fi

echo "$target" > "$STATE_FILE"
log "flip complete. live color = $target"

if [ -n "$active" ]; then
	log "previous color ab-$active left running for instant rollback: ./deploy.sh rollback"
fi

# Reclaim disk from images that no longer back any container. The current and
# previous colors are still running (plus caddy / any tools), so their images
# are in-use and prune NEVER touches them — this only removes stale images left
# by older deploys. Self-cleaning, so the host needs no separate prune cron.
log "pruning unused images"
docker image prune -af >/dev/null 2>&1 || true
