import { isTerminalReport } from "../keystrokes";

/** Clipboard ownership counts guest clicks, unlike work-status reply tracking. */
export function isClipboardUserInput(data: string): boolean {
  if (!data) return false;
  const sgr = /^\x1b\[<(\d+);\d+;\d+[Mm]$/.exec(data);
  const urxvt = /^\x1b\[(\d+);\d+;\d+M$/.exec(data);
  let button: number | undefined;
  if (sgr) button = Number(sgr[1]);
  else if (urxvt) button = Number(urxvt[1]) - 32;
  else if (/^\x1b\[M[\s\S]{3}$/.test(data)) button = data.charCodeAt(3) - 32;
  if (button !== undefined) {
    return Number.isInteger(button) && button >= 0 && button <= 255 && (button & (32 | 64)) === 0;
  }
  if (isTerminalReport(data)) return false;
  // Device attributes/status, cursor position, and terminal string replies are
  // generated by the viewing engine without a user gesture.
  if (/^\x1b\[(?:[?>]?[\d;]*c|[\d;]+[Rn]|[?>][\d;]*u|\??[\d;]+\$y|[\d;]*t)$/.test(data)) return false;
  if (/^(?:\x1b[\]P^_]|[\x90\x9d\x9e\x9f])/.test(data)) return false;
  return true;
}
