[package]
name = "antgrid-relay-compat-client"
version = "0.1.0"
edition = "2024"
publish = false
license = "Elastic-2.0"

[workspace]

[dependencies]
anyhow = "1"
futures-util = { version = "0.3", features = ["sink"] }
iroh-relay = "=1.0.0"
iroh-base = "=1.0.0"
iroh-dns = "=1.0.0"
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
rustls-pemfile = "2"
tokio = { version = "1", features = ["full"] }
