import 'dart:convert';
import 'package:cryptography/cryptography.dart';
import 'package:test/test.dart';
import 'package:antgrid_relay_client/src/account_membership_sign.dart';

// Small helper: encode bytes as lowercase hex.
String _hex(List<int> bytes) =>
    bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();

void main() {
  // Fixed inputs (mirrors the bun golden-vector snippet):
  //   agentDeviceId="a", phoneDeviceId="p",
  //   phonePubkey        = 32 bytes of 0x01 (base64),
  //   accountDevicePubkey = 32 bytes of 0x04 (base64),
  //   nonce              = 24 bytes of 0x03 (base64).
  final phonePubB64 = base64.encode(List.filled(32, 0x01));
  final accountPubB64 = base64.encode(List.filled(32, 0x04));
  final nonceB64 = base64.encode(List.filled(24, 0x03));

  // Golden hex generated by running the TS builder with identical inputs:
  //   cd bridge && bun -e 'import {buildMembershipSigBody} from "./src/account-membership-verify"; ...'
  const goldenHex =
      '616e74677269642e6163636f756e742d6d656d626572736869702e76310061007000'
      '010101010101010101010101010101010101010101010101010101010101010100'
      '040404040404040404040404040404040404040404040404040404040404040400'
      '030303030303030303030303030303030303030303030303';

  test('buildMembershipSigBody matches TS golden vector', () {
    final body = buildMembershipSigBody(
      agentDeviceId: 'a',
      phoneDeviceId: 'p',
      phonePubkey: phonePubB64,
      accountDevicePubkey: accountPubB64,
      nonce: nonceB64,
    );
    expect(_hex(body), equals(goldenHex));
  });

  test('signAccountMembership + Ed25519.verify round-trip returns true', () async {
    // Deterministic Ed25519 seed (32 bytes of 0xAB).
    final seed = List.filled(32, 0xAB);
    final kp = await Ed25519().newKeyPairFromSeed(seed);
    final pub = await kp.extractPublicKey();
    final pubB64 = base64.encode(pub.bytes);

    final sigB64 = await signAccountMembership(
      agentDeviceId: 'a',
      phoneDeviceId: 'p',
      phonePubkey: phonePubB64,
      accountDevicePubkey: pubB64,
      nonce: nonceB64,
      accountDevicePrivSeed: seed,
    );

    final body = buildMembershipSigBody(
      agentDeviceId: 'a',
      phoneDeviceId: 'p',
      phonePubkey: phonePubB64,
      accountDevicePubkey: pubB64,
      nonce: nonceB64,
    );
    final ok = await Ed25519().verify(
      body,
      signature: Signature(base64.decode(sigB64), publicKey: pub),
    );
    expect(ok, isTrue);
  });

  test('seed->pubkey is internally consistent with accountDevicePubkey', () async {
    // The pubkey derived from the seed must match what we pass as accountDevicePubkey.
    final seed = List.filled(32, 0xAB);
    final kp = await Ed25519().newKeyPairFromSeed(seed);
    final pub = await kp.extractPublicKey();
    final pubB64 = base64.encode(pub.bytes);

    // Sign using pubB64 as accountDevicePubkey — must not throw and must verify.
    final sigB64 = await signAccountMembership(
      agentDeviceId: 'a',
      phoneDeviceId: 'p',
      phonePubkey: phonePubB64,
      accountDevicePubkey: pubB64,
      nonce: nonceB64,
      accountDevicePrivSeed: seed,
    );

    final body = buildMembershipSigBody(
      agentDeviceId: 'a',
      phoneDeviceId: 'p',
      phonePubkey: phonePubB64,
      accountDevicePubkey: pubB64,
      nonce: nonceB64,
    );
    final ok = await Ed25519().verify(
      body,
      signature: Signature(base64.decode(sigB64), publicKey: pub),
    );
    // Confirms seed→pubkey→verify is consistent.
    expect(ok, isTrue);
  });

  test('signAccountMembership throws on wrong seed length', () async {
    expect(
      () => signAccountMembership(
        agentDeviceId: 'a',
        phoneDeviceId: 'p',
        phonePubkey: phonePubB64,
        accountDevicePubkey: accountPubB64,
        nonce: nonceB64,
        accountDevicePrivSeed: List.filled(16, 0x00),
      ),
      throwsA(isA<ArgumentError>()),
    );
  });
}
