export type ApiError =
  | "UNAUTHENTICATED"
  | "NOT_FOUND"
  | "BAD_REQUEST"
  | "RATE_LIMITED"
  | "INVALID_CODE"
  | "CODE_EXPIRED"
  | "AUTHORIZATION_PENDING"
  | "DEVICE_LIMIT_REACHED"
  | "LICENSE_EXPIRED"
  | "LICENSE_REVOKED"
  | "DEVICE_HARDWARE_MISMATCH"
  | "LICENSE_INVALID";
